#!/usr/bin/env python3
import sys
import re
import shutil
from git import Repo

LANGS = ['py', 'php', 'js', 'sql']
LANG = 'py'

if len(sys.argv) < 2:
    exit("[-] Uh oh, problem name is missing")
problem = sys.argv[1]

if len(sys.argv) == 3 and sys.argv[2] in LANGS:
    LANG = sys.argv[2]

repo = Repo('../.git/')

problem_filename = re.sub(
    r"[^a-z0-9\s]", "", problem.lower()).replace(" ", "_") + "." + LANG
shutil.copy(f"./template.{LANG}", problem_filename)
print(f"[+] {problem_filename} created!")

repo.index.add(f"/Users/bl4de/playground/cs/LeetCode/{problem_filename}")
repo.index.commit(f"[LeetCode] {problem} - initial commit")
print(f"[+] {problem_filename} commited!")

origin = repo.remote('origin')
origin.push()
print(f"[+] {problem_filename} initial commit pushed!")
print(f"[LeetCode] {problem} - in progress")
