#!/usr/bin/env python3
import sys
import re
import shutil
from git import Repo

if len(sys.argv) < 2:
    exit("[-] Uh oh, problem name is missing")
problem = sys.argv[1]

lang = 'py' if len(sys.argv) == 2 else sys.argv[2]
repo = Repo('../.git/')

problem_filename = re.sub(
    r"[^a-z0-9\s]", "", problem.lower()).replace(" ", "_") + "." + lang
shutil.copy(f"./template.{lang}", problem_filename)
print(f"[+] {problem_filename} created!")

repo.index.add(f"/Users/bl4de/playground/cs/LeetCode/{problem_filename}")
repo.index.commit(f"[LeetCode] {problem} - initial commit")
print(f"[+] {problem_filename} commited!")

origin = repo.remote('origin')
origin.push()
print(f"[+] {problem_filename} initial commit pushed!")
print(f"[LeetCode] {problem} - in progress")
